### PR TITLE
Fix postprocessing of disassembled version in latest version spectool-wasm.

### LINKED ISSUE #124: Comments have to be removed
Screenshot 2024-10-19 at 15 19 42

### PR DESCRIPTION
**Pull request by tomusdrw**
Fixes #124 

Also adds line numbers via `CodeMirror` and removes unused deps.

### CODE REVIEW

File: src/components/ProgramLoader/Assembly.tsx [hunk 1]
```diff
@@ -44,29 +44,16 @@ function assemblyFromInputProgram(initialState: InitialState, program: number[])
       // remove leading whitespace
       l = l.trim();
       // replace labels
-      l = l.replace(/: @(.+)$/, "@block$1:");
+      l = l.replace(/(: )?@(.+)$/, "@block$2$1");
+      // remove line number
+      l = l.replace(/^[0-9]+: /, "\t");
+      // fix ecalli comments?
```
Comment (wkwiatek) [inline src/components/ProgramLoader/Assembly.tsx:50]: Could you please shed a little bit more light on why is it necessary? I mean, not only this line but whole `fixedLines`.  

Ideally would see it as the comment inside the code.

**Review by wkwiatek — COMMENTED** [review]
Looks good! Thanks for cleanup. 

Just a little remark about the whole reasoning behind fixing lines on assemblify.

File: src/components/ProgramLoader/Assembly.tsx (hunk 1 above)
Comment (tomusdrw) [reply src/components/ProgramLoader/Assembly.tsx:61]: Sure thing! Added some in-code comments.

**Review by wkwiatek — APPROVED** [review]
